authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('inscription', views.SignUpPageView.as_view(), name='subscribe'),
    path('', views.LoginPageView.as_view(), name='home'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    path('flux', views.TicketsListView.as_view(), name='flux'),
    path('abonnements', views.FollowCreationView.as_view(), name='follow'),
    path('désabonnement/<int:pk>/', views.FollowDeleteView.as_view(), name='follow_delete'),
    path('ticket/<int:pk>/', views.TicketUpdateView.as_view(), name='ticket'),
    path('ticket/delete/<int:pk>/', views.TicketDeleteView.as_view(), name='ticket_delete'),
    path('ticket', views.TicketCreationView.as_view(), name='ticket_create'),
    path('critique', views.ReviewCreationView.as_view(), name='review_create'),
    path('critique/<int:id_ticket>/', views.ReviewResponseView.as_view(), name='review_response'),
    path('critique/update/<int:pk>/', views.ReviewUpdateView.as_view(), name='review_update'),
    path('critique/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('posts', views.PostsPageView.as_view(), name='posts'),
]

projet/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('authentication.urls')),
    path('forum/', include('forum.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

        labels = {
            'username': 'Nom d\'utilisateur'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Mot de passe'
        self.fields['password2'].label = 'Confirmer le mot de passe'


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=63, label='Nom d’utilisateur')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Mot de passe')

authentication/views.py
from django.contrib.auth import views
from django.urls import reverse_lazy
from django.views import generic

from .forms import SignUpForm


class SignUpPageView(generic.CreateView):
    form_class = SignUpForm
    template_name = 'authentication/subscribe.html'
    success_url = reverse_lazy('authentication:home')


class LoginPageView(views.LoginView):
    template_name = 'authentication/home.html'
    next_page = reverse_lazy('forum:flux')


class LogoutPageView(views.LogoutView):
    next_page = reverse_lazy('authentication:home')

authentication/templates/authentication/home.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

<p>{{ message }}</p>
<div class="row">
    <div class="col-sm-1">
          </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Inscrivez-vous maintenant</h5>
                {% url 'authentication:subscribe' as url_subscribe %}
                {% bootstrap_button "S'inscrire" button_type="link" button_class="btn-primary m-2 mt-4" href=url_subscribe %}
            </div>
        </div>
    </div>
    <div class="col-sm-1">
          </div>
    <div class="col-sm-4 ">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Connectez-vous</h5>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% bootstrap_button "Se connecter" button_type="submit" button_class="btn-primary m-2 mt-4" %}
                </form>
            </div>

        </div>
    </div>
</div>
</form>
{% endblock content %}

authentication/templates/authentication/login.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

<p>{{ message }}</p>
<div class="row">
    <div class="col-sm-1">
          </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Inscrivez-vous maintenant</h5>
                {% url 'authentication:subscribe' as url_subscribe %}
                {% bootstrap_button "S'inscrire" button_type="link" button_class="btn-primary m-2 mt-4" href=url_subscribe %}
            </div>
        </div>
    </div>
    <div class="col-sm-1">
          </div>
    <div class="col-sm-4 ">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Connectez-vous</h5>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% bootstrap_button "Se connecter" button_type="submit" button_class="btn-primary m-2 mt-4" %}
                </form>
            </div>

        </div>
    </div>
</div>
</form>
{% endblock content %}

authentication/templates/authentication/subscribe.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

<div class="row justify-content-center">
    <div class="card text-center m-0 p-0 mt-5" style="width: 35%;">
        <div class="card-header">
            <h1>Inscrivez-vous</h1>
        </div>
        <br/>
        <div class="user-card text-center justify-content-center">
            <form action="" method="POST" class="form">
                {% csrf_token %}
                <label class="form-control">{{ form.username.label }}</label>
                {{ form.username }}
                {% for error in form.username.errors %}
                <p>{{ error }}</p>
                {% endfor %}
                <label class="form-control">{{ form.password1.label }}</label>
                {{ form.password1 }}
                {% for error in form.password1.errors %}
                <p>{{ error }}</p>
                {{ form.password1.help_text }}
                {% endfor %}
                <label class="form-control">{{ form.password2.label }}</label>
                {{ form.password2 }}
                {% for error in form.password2.errors %}
                <p>{{ error }}</p>
                {{ form.password2.help_text }}
                {% endfor %}
                {% url 'authentication:home' as url_login %}
                <br/>
                {% bootstrap_button "Retour" button_type="link" button_class="btn-primary m-2 mt-4" href=url_login%}
                {% bootstrap_button "S'inscrire" button_type="submit" button_class="btn-primary m-2 mt-4" %}
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
<!--        var form_fields = document.getElementById('id_username')-->
<!--        form_fields.placeholder='Nom d\'utilisateur';-->
<!--        form_fields.className += ' form-control'-->
<!--        form_fields= document.getElementById('id_password1')-->
<!--        form_fields.placeholder='Mot de passe';-->
<!--        form_fields.className += ' form-control'-->
<!--        form_fields= document.getElementById('id_password2')-->
<!--        form_fields.placeholder='Confirmer mot de passe';-->
<!--        form_fields.className += ' form-control'-->

</script>
{% endblock content %}