forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    path('flux', views.TicketsListView.as_view(), name='flux'),
    path('abonnements', views.FollowCreationView.as_view(), name='follow'),
    path('désabonnement/<int:pk>/', views.FollowDeleteView.as_view(), name='follow_delete'),
    path('ticket/<int:pk>/', views.TicketUpdateView.as_view(), name='ticket'),
    path('ticket/delete/<int:pk>/', views.TicketDeleteView.as_view(), name='ticket_delete'),
    path('ticket', views.TicketCreationView.as_view(), name='ticket_create'),
    path('critique', views.ReviewCreationView.as_view(), name='review_create'),
    path('critique/<int:id_ticket>/', views.ReviewResponseView.as_view(), name='review_response'),
    path('critique/update/<int:pk>/', views.ReviewUpdateView.as_view(), name='review_update'),
    path('critique/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('posts', views.PostsPageView.as_view(), name='posts'),
]

projet/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('authentication.urls')),
    path('forum/', include('forum.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    title = models.CharField('Titre', max_length=128)
    description = models.TextField('Description', max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField('Image', upload_to='images/', null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, related_name='reviews', on_delete=models.CASCADE)
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    rating = models.PositiveSmallIntegerField('Note',
                                              # validates that rating must be between 0 and 5
                                              validators=[MinValueValidator(0), MaxValueValidator(5)],
                                              choices=RATING_CHOICES)
    headline = models.CharField('Titre', max_length=128)
    body = models.TextField('Commentaire', max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                      related_name='followed_by')

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user')

forum/forms.py
from django.contrib.auth.forms import UserModel
from django.forms import ModelForm
from django import forms
from forum.models import Ticket, Review, UserFollows


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ('title', 'description', 'image')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('headline', 'rating', 'body')

        widgets = {
            'headline': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['rating'].widget = forms.RadioSelect(choices=self.Meta.model.RATING_CHOICES)


class UserFollowsForm(ModelForm):
    class Meta:
        model = UserFollows
        fields = [
            'followed_user',
        ]
    followed_user = forms.ModelChoiceField(
        queryset=None,
        label="Suivre l'utilisateur :",
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

        self.fields['followed_user'].queryset = UserModel.objects.exclude(username=user.username)

forum/views.py
from itertools import chain

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Value, CharField, Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView

from forum.models import Ticket, Review, UserFollows
from .forms import TicketForm, ReviewForm, UserFollowsForm


# user = User.objects.all().prefetch_related('ticket_set', 'ticket_set__review_set')

class TicketsListView(LoginRequiredMixin, ListView):
    # Feed the flux page
    model = Ticket
    template_name = 'forum/flux.html'
    context_object_name = 'tickets'

    def get_context_data(self, **kwargs):
        # Get users.id followed by request.user
        followed_users_id = UserFollows.objects.filter(
            user=self.request.user
        ).values_list("followed_user_id", flat=True)

        # Get reviews make by user followed
        reviews_followed_users = (
            Review.objects.filter(
                Q(user__in=followed_users_id) | Q(user=self.request.user.id)
            ).select_related()
        ).annotate(content_type=Value("REVIEW", CharField()))

        # Get tickets make by user followed
        tickets_followed_users = (
            Ticket.objects.filter(
                Q(user__in=followed_users_id) | Q(user=self.request.user.id)
            ).select_related()
        ).annotate(content_type=Value("TICKET", CharField()))

        # Get users.id who follow request.user
        following_users_id = UserFollows.objects.filter(
            followed_user=self.request.user
        ).values_list("user_id", flat=True)

        # Get reviews make by them for request.user tickets
        reviews_following_users = (
            Review.objects.filter(
                Q(user__in=following_users_id) & Q(ticket__user=self.request.user.id)
            )
                .select_related()
                .annotate(content_type=Value("REVIEW", CharField()))
        )

        context = super().get_context_data(**kwargs)
        context['feeds'] = sorted(chain(reviews_followed_users,
                                        tickets_followed_users,
                                        reviews_following_users, ), key=lambda instance: instance.time_created,
                                  reverse=True)

        return context


class PostsPageView(LoginRequiredMixin, ListView):
    # Display tickets and reviews of logged in user only
    model = Ticket
    template_name = 'forum/posts.html'
    context_object_name = 'tickets'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tickets = Ticket.objects.filter(user=self.request.user).order_by('-time_created').annotate(
            content_type=Value("TICKET", CharField()))
        reviews = Review.objects.filter(user=self.request.user).order_by('-time_created').annotate(
            content_type=Value("REVIEW", CharField()))
        context['feeds'] = sorted(chain(tickets, reviews), key=lambda instance: instance.time_created,
                                  reverse=True)

        return context


class TicketCreationView(LoginRequiredMixin, CreateView):
    # Create a ticket
    model = Ticket
    template_name = 'forum/ticket_create.html'
    form_class = TicketForm
    success_url = reverse_lazy('forum:flux')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    # Edit a ticket
    model = Ticket
    form_class = TicketForm
    template_name = 'forum/ticket_update.html'
    success_url = reverse_lazy('forum:flux')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TicketDeleteView(LoginRequiredMixin, DeleteView):
    # Delete a ticket
    model = Ticket
    template_name = 'forum/ticket_delete.html'
    success_url = reverse_lazy('forum:flux')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class ReviewResponseView(LoginRequiredMixin, CreateView):
    # Create a review in response to a ticket
    model = Review
    template_name = 'forum/review.html'
    form_class = ReviewForm
    success_url = reverse_lazy('forum:flux')

    _ticket = None

    @property
    def ticket(self):
        if self._ticket is None:
            self._ticket = get_object_or_404(Ticket.objects.all(), id=self.kwargs['id_ticket'])
        return self._ticket

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket'] = self.ticket
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.ticket = self.ticket
        return super().form_valid(form)


class ReviewCreationView(LoginRequiredMixin, TemplateView):
    # Create a review and a ticket in one go
    template_name = 'forum/review_create.html.'
    form_review = ReviewForm()
    form_ticket = TicketForm()

    def post(self, request, *args, **kwargs):
        form_review = ReviewForm(request.POST, request.FILES, prefix="review")
        form_ticket = TicketForm(request.POST, request.FILES, prefix="ticket")

        if form_review.is_valid() and form_ticket.is_valid():
            ticket = form_ticket.save(commit=False)
            form_ticket.instance.user = self.request.user
            ticket.save()
            review = form_review.save(commit=False)
            form_review.instance.user = self.request.user
            review.ticket = form_ticket.save()
            review.save()
            return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        form_ticket = TicketForm(prefix="ticket")
        form_review = ReviewForm(prefix="review")
        return {"form_ticket": form_ticket, "form_review": form_review}

    def get_success_url(self):
        return reverse_lazy('forum:flux')


class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    # Edit a review
    model = Review
    form_class = ReviewForm
    template_name = 'forum/review_update.html'
    success_url = reverse_lazy('forum:flux')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    # Delete a review
    model = Review
    template_name = 'forum/review_delete.html'
    success_url = reverse_lazy('forum:flux')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class FollowCreationView(LoginRequiredMixin, CreateView):
    # Allowed follows and display lists of followers and followed
    model = UserFollows
    template_name = 'forum/abonnements.html'
    form_class = UserFollowsForm
    success_url = reverse_lazy('forum:follow')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_following = UserFollows.objects.all().select_related()
        user_followed = UserFollows.objects.all().select_related()

        context["current_user"] = self.request.user
        context["following_users"] = sorted(
            user_following,
            key=lambda user: user.user.username,
            reverse=False,
        )
        context["followed_users"] = sorted(
            user_followed,
            key=lambda user: user.followed_user.username,
            reverse=False,
        )
        return context


class FollowDeleteView(LoginRequiredMixin, DeleteView):
    # Delete the followed
    model = UserFollows
    template_name = 'forum/désabonnement.html'
    success_url = reverse_lazy('forum:follow')

forum/templates/forum/abonnements.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}
<br/>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="card w-50">
            <div class="row">
                <h5 style="text-align: center">Suivre d'autres utilisateurs</h5>
                <div class="col-sm-10">
                    {{form.as_p}}
                </div>
                <div class="col-sm-2 mb-2" style="text-align: end">
                    {% bootstrap_button "Suivre" button_type="submit" button_class="btn-primary" %}
                </div>
            </div>
        </div>
    </div>
</form>
<br/>
<br/>
<div class="row justify-content-center">
    <div class="card w-50 p-0">
        <div class="card-header" style="text-align: center">
            Abonnements
        </div>
        <ul class="list-group list-group-flush">
            {% for user in followed_users %}
            {% if user.user == current_user %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-sm-9">
                        <p class="card-text">{{ user.followed_user }}</p>
                    </div>
                    <div class="col-sm-3 pr-0 mr-0" style="text-align: end">
                        <a href="{% url 'forum:follow_delete' pk=user.id %}" class=" btn btn-danger btn-sm">Se désabonner</a>
                    </div>
                </div>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
<br/>

<div class="row justify-content-center">
    <div class="card w-50 p-0">
        <div class="card-header" style="text-align: center">
            Abonnés
        </div>
        <ul class="list-group list-group-flush">
            {% for user in following_users %}
            {% if user.followed_user == current_user %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-sm-9">
                        <p class="card-text">{{ user.user }}</p>
                    </div>
                </div>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

forum/templates/forum/désabonnement.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}


<br/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Voulez-vous arrêter de suivre "{{ userfollows.followed_user }}"?</h5>
                <button type="submit" class="btn btn-light">Confirmer</button>
            </div>
        </div>
    </div>
</form>
<div class="row justify-content-center">

    <a href="/forum/abonnements" class="btn btn-secondary" style="max-width: 18rem;" role="button">Annuler la suppression</a>
</div>
{% endblock %}

forum/templates/forum/flux.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-3">
        {% bootstrap_button "Demander une critique" button_type="link" button_class="btn-primary m-2 mt-4" href="ticket" %}
    </div>
    <div class="col-sm-3">
        {% bootstrap_button "Créer une critique" button_type="link" button_class="btn-primary m-2 mt-4" href="critique" %}
    </div>
</div>


{% if feeds %}
{% for feed in feeds %}
{% if feed.content_type == 'TICKET' %}
{% include 'forum/ticket_card.html'  with ticket=feed with_edit=True %}
{% block ticket_card %}
{% endblock %}
{% elif feed.content_type == 'REVIEW' %}
{% include 'forum/review_card.html' with review=feed %}
{% endif %}
{% endfor %}
{% else %}
<br/>
<p style="text-align: center">Il n'y a ni ticket ni critique à afficher pour l'instant.</p>
{% endif %}


{% endblock content %}

forum/templates/forum/posts.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

<div class="row justify-content-center">
        <div class="col-sm-1">
          </div>
    <div class="col-sm-3">
        {% bootstrap_button "Demander une critique" button_type="link" button_class="btn-primary m-2 mt-4" href="ticket" %}
    </div>
    <div class="col-sm-3">
        {% bootstrap_button "Créer une critique" button_type="link" button_class="btn-primary m-2 mt-4" href="critique" %}
    </div>
</div>


{% if feeds %}
    {% for feed in feeds %}
        {% if feed.content_type == 'TICKET' %}
            {% include 'forum/ticket_card.html'  with ticket=feed with_edit=True %}
            {% block ticket_card %}
            {% endblock %}
        {% elif feed.content_type == 'REVIEW' %}
            {% include 'forum/review_card.html' with review=feed %}
        {% endif %}
    {% endfor %}
{% else %}
<br/>
    <div style="text-align:center">Vous n'avez pas publié de critique ni de ticket.</div>
{% endif %}

{% endblock content %}

forum/templates/forum/rating.html
{% block rating_card %}


<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1">
  <label class="form-check-label" for="inlineRadio1">1</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="2">
  <label class="form-check-label" for="inlineRadio2">2</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="3">
  <label class="form-check-label" for="inlineRadio3">3</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="4">
  <label class="form-check-label" for="inlineRadio4">4</label>
</div>
<div class="form-check form-check-inline">
  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio5" value="5">
  <label class="form-check-label" for="inlineRadio5">5</label>
</div>


{% endblock %}

forum/templates/forum/review.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}
<div class="row justify-content-center">
    <div class="card w-50">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% include 'forum/ticket_card.html' with ticket=ticket with_edit=False %}
            {% block ticket_card %}
            {% endblock %}


            {{form.headline.label}}
            {{form.headline}}
            {{form.rating.label}}
            {{form.rating}}
            {{form.body.label}}
            {{form.body}}


            {% bootstrap_button "Envoyer" button_type="submit" button_class="btn-primary m-2 mt-4" %}
        </form>
        {% endblock content %}
    </div>
</div>

forum/templates/forum/review_card.html
{% block review_card %}

<div class="row justify-content-center">
    <div class="card w-50">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-7" style="font-style:italic">
                    {% if review.user.id == user.pk %}
                    Vous avez publié une critique
                    {% else %}
                    {{review.user.username}} a publié une critique
                    {% endif %}
                </div>
                <div class="col-sm-5" style="text-align: end; font-style:italic">
                    {{review.time_created}}
                </div>
            </div>
            <br/>
            <div class="row">
                <h5>Titre : {{review.headline}} -
                    {% if review.rating >= 1 %}
                    ★
                    {% endif %}
                    {% if review.rating >= 2 %}
                    ★
                    {% endif %}
                    {% if review.rating >= 3 %}
                    ★
                    {% endif %}
                    {% if review.rating >= 4 %}
                    ★
                    {% endif %}
                    {% if review.rating == 5 %}
                    ★
                    {% endif %}
                </h5>
                <p>Commentaire : {{review.body |linebreaksbr}}</p>
            </div>
            <div class="col-sm-10">
                {% if review.user.id == user.pk %}
                <small><a href="{% url 'forum:review_update' pk=review.id%}">Modifier</a></small>
                {% endif %}
                {% if review.user.id == user.pk %}
                <small><a href="{% url 'forum:review_delete' pk=review.id %}">Supprimer</a></small>
                {% endif %}
                <div class="col-sm-12">
                </div>

            </div>

            <div class="row">
                {% include 'forum/ticket_card.html' with ticket=review.ticket with_edit=False %}
                {% block ticket_card %}
                {% endblock %}
                <br/>
            </div>
    </div>

    </form>
    <br/>
</div>
</div>


{% endblock %}

forum/templates/forum/review_create.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}
<div class="row justify-content-center">
    <div class="card w-50">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h5>Livre / Article</h5>
            {{form_ticket.as_p}}
            <h5>Critique</h5>
            {{form_review.as_p}}
            {% bootstrap_button "Envoyer" button_type="submit" button_class="btn-primary m-2 mt-4" %}
        </form>
        {% endblock content %}
    </div>
</div>

forum/templates/forum/review_delete.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

{% include 'forum/review_card.html' %}
{% block review_card %}
{% endblock %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Voulez-vous supprimer la critique ?</h5>
                <button type="submit" class="btn btn-light">Confirmer</button>
            </div>
        </div>
    </div>
</form>
<div class="row justify-content-center">

    <a href="/forum/flux" class="btn btn-secondary" style="max-width: 18rem;" role="button">Annuler la suppression</a>
</div>
{% endblock %}

forum/templates/forum/review_update.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

<br/>
<br/>
<div class="row justify-content-center">
    {% include 'forum/ticket_card.html' with ticket=review.ticket with_edit=False %}
    {% block ticket_card %}
    {% endblock %}
    <br/>
    <div class="card w-50 p-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>{{form.headline.label}} : {{form.headline}}</div>
            <br/>
            <div>{{form.rating.label}} : {{form.rating}} / 5</div>
            <br/>
            <div>{{form.body.label}} : {{form.body}}</div>
            {% bootstrap_button "Envoyer" button_type="submit" button_class="btn-primary m-2 mt-4" %}
            {% bootstrap_button "Annuler" button_type="link" button_class="btn btn-outline-secondary m-2 mt-4" href="/forum/flux" %}
        </form>
    </div>
</div>


{% endblock content %}

forum/templates/forum/ticket_card.html
{% block ticket_card %}

<div class="row justify-content-center">
    <div class="card w-50">

        <div class="row">
            <div class="col-sm-7" style="font-style:italic">
                {% if ticket.user.id == user.pk %}
                Vous avez demandé une critique
                {% else %}
                {{ticket.user.username}} a demandé une critique
                {% endif %}
            </div>
            <div class="col-sm-5" style="text-align: end; font-style:italic">
                {{ticket.time_created}}
            </div>

            <div class="row justify-content-center">
                <div class="col-sm-1">
                </div>
                {% if ticket.image %}
                <img class="card-img w-25 col-sm-6" src={{ticket.image.url}} alt="Couverture non disponible">
                {% endif %}
            </div>
            <div class="card-body">
                <h5 class="card-title">Titre : {{ticket.title}}</h5>
                <p class="card-text">Description : {{ticket.description |linebreaksbr}}</p>
            </div>
            <div class="col-sm-10">
                {% if ticket.user.id == user.pk %}
                <small><a href="{% url 'forum:ticket' pk=ticket.id %}">Modifier</a></small>
                {% endif %}
                {% if ticket.user.id == user.pk %}
                <small><a href="{% url 'forum:ticket_delete' pk=ticket.id %}">Supprimer</a></small>
                {% endif %}
                <div class="col-sm-12">
                </div>

                <div class="col-sm-4">
                    {% if not ticket.reviews.all and with_edit %}
                    <a href="{% url 'forum:review_response' id_ticket=ticket.id %}" class="btn btn-primary m-2 mt-4"
                       style="align-content:end">Répondre une
                        critique</a>

                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

forum/templates/forum/ticket_create.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

    <br/>
    <br/>
<div class="row justify-content-center">
    <div class="card w-50">


        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            {% bootstrap_button "Envoyer" button_type="submit" button_class="btn-primary m-2 mt-4" %}
        </form>
    </div>
</div>
{% endblock content %}

forum/templates/forum/ticket_delete.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}


{% include 'forum/ticket_card.html' with ticket=ticket with_edit=False %}
{% block ticket_card %}
{% endblock %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Voulez-vous supprimer le ticket "{{ object.title }}"?</h5>
                <p class="card-text">La suppression du ticket provoque la suppression de la critique associée.</p>
                <button type="submit" class="btn btn-light">Confirmer</button>
            </div>
        </div>
    </div>
</form>
<div class="row justify-content-center">

    <a href="/forum/flux" class="btn btn-secondary" style="max-width: 18rem;" role="button">Annuler la suppression</a>
</div>
{% endblock %}

forum/templates/forum/ticket_update.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}

<br/>
<br/>
<div class="row justify-content-center">
    <div class="card w-50">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p|linebreaksbr}}
            {% bootstrap_button "Envoyer" button_type="submit" button_class="btn-primary m-2 mt-4" %}
            {% bootstrap_button "Annuler" button_type="link" button_class="btn btn-outline-secondary m-2 mt-4" href="/forum/flux" %}
        </form>
    </div>
</div>


{% endblock content %}